name: Deploy latest build

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: prod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            docker pull morozoffnor/kuskiminiapps:latest
            cd /${{ secrets.SSH_USER }}/kuski-miniapp && docker compose up -d
      
