name: Build and push (tag)

on:
  workflow_dispatch:
    inputs:
      tag:
        default: 'latest'
        description: 'Docker image tag'
        required: true
      ghcr:
        default: 'false'
        description: 'Push to GitHub Container Registry'
        required: false
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Build and push (DockerHub)
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kuskiminiapps:${{ github.event.inputs.tag }}
      - name: Build and push (GitHub Registry)
        if: ${{ github.event.inputs.ghcr == 'true' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kuskiminiapps:${{ github.event.inputs.tag }}
